name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Jalankan pipeline setiap kali ada perubahan di branch 'main'
  pull_request:
    branches:
      - main  # Jalankan pipeline untuk setiap pull request ke branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Mesin virtual yang akan digunakan

    steps:
      # Langkah pertama: Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v2

      # Langkah kedua: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Langkah ketiga: Install dependencies untuk frontend (React)
      - name: Install frontend dependencies
        working-directory: ./ddk_web
        run: npm install

      # Langkah keempat: Build frontend (React)
      - name: Build frontend
        working-directory: ./ddk_web
        run: npm run build

      # Langkah kelima: Install dependencies untuk backend (Express)
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # Langkah keenam: Jalankan pengujian backend
      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      # Langkah ketujuh: Deploy aplikasi (optional)
      # Tambahkan langkah deployment di sini jika sudah siap untuk deployment otomatis
